name: Build and Publish Library

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run unit tests
        run: npm run test:unit
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: "./dist"
  publish-npm:
    runs-on: ubuntu-latest
    permissions: 
      packages: write
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: "./dist"
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
  